Repository RedHatQE/openshift-python-utilities, pull requests merged in 2022-11, with the labels that each got.

#60 update must gather command, based on recent changes
  ocp_utilities/must_gather.py
Labels: verified, size/XS, Approved-by-rnetser, branch-main

#68 Remove version from setup.cfg
  setup.cfg
Labels: verified, size/XS, Approved-by-rnetser, branch-main

#70 add remote python debugger
  ocp_utilities/debugger.py
  requirements.txt
Labels: verified, size/XS, Approved-by-rnetser, branch-main

#74 add remote python debugger
  ocp_utilities/debugger.py
  requirements.txt
Labels: verified, size/S, Approved-by-rnetser, branch-v4.11

#66 DynamicClassCreator: Use self.res
  ocp_utilities/infra.py
Labels: verified, size/XS, branch-main

#78 python remote debugger: get port from os env
  ocp_utilities/debugger.py
Labels: verified, size/XS, Approved-by-rnetser, branch-main
