Repository RedHatQE/openshift-python-utilities, pull requests merged in 2023-03, with the labels that each got.

#147 Update pre-commit hooks
  .pre-commit-config.yaml
Labels: verified, size/XS, branch-main

#155 Add operators.py with wait for operator ready
  .flake8
  ocp_utilities/operators.py
  tox.ini
Labels: size/L, verified, Approved-by-rnetser, branch-main

#162 Add uninstall_operator function
  ocp_utilities/operators.py
Labels: verified, size/S, Approved-by-myakove, branch-main

#166 operator functions - set defaults
  ocp_utilities/operators.py
Labels: verified, size/XS, Approved-by-myakove, branch-main

#176 Replace setup.py and setup.cfg (#170)
  .gitignore
  .release-it.json
  README.md
  VERSION
  pyproject.toml
  setup.cfg
  setup.py
Labels: size/L, verified, Approved-by-myakove, branch-v4.12
