Repository RedHatQE/openshift-python-utilities, pull requests merged in 2023-06, with the labels that each got.

#222 Support install operator using iib (index image)
  ocp_utilities/operators.py
Labels: size/L, verified, Approved-by-rnetser, branch-main, can-be-merged

#225 Support install operator using iib (index image) (#222)
  ocp_utilities/operators.py
Labels: size/L, verified, branch-v4.13

#227 Update OWNERS
  OWNERS
Labels: size/XS, Approved-by-myakove, branch-main

#228 Set unique catalog source name for each operator
  ocp_utilities/operators.py
Labels: verified, size/XS, Approved-by-rnetser, branch-main, Approved-by-omrirh, can-be-merged

#232 Set unique catalog source name for each operator (#228)
  ocp_utilities/operators.py
Labels: verified, size/XS, branch-v4.14, target-branch-v4.13

#234 Set unique catalog source name for each operator (#228) (#232)
  ocp_utilities/operators.py
Labels: verified, size/XS, branch-v4.13
