Repository RedHatQE/openshift-python-utilities, pull requests merged in 2023-08, with the labels that each got.

#244 Make project poetry based instead of setuptools
  .release-it.json
  README.md
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: verified, branch-main, size/XXL, can-be-merged, ApprovedBy-myakove

#254 Ignore urllib3 `InsecureRequestWarning` warnings
  .flake8
  ocp_utilities/infra.py
Labels: verified, size/XS, branch-main, can-be-merged, ApprovedBy-myakove

#258 Add wait for subscription installedCSV
  ocp_utilities/operators.py
Labels: verified, size/XS, branch-main, can-be-merged, ApprovedBy-myakove, cherry-pick-v4.14
