Repository RedHatQE/openshift-python-utilities, pull requests merged in 2023-01, with the labels that each got.

#82 Added pod validating method assert_pods_failed_or_pending to check pods health
  ocp_utilities/exceptions.py
  ocp_utilities/infra.py
Labels: verified, size/S, Approved-by-myakove, Approved-by-rnetser, branch-main

#91 Remove typing hint from assert_pods_failed_or_pending
  ocp_utilities/infra.py
Labels: verified, size/XS, Approved-by-rnetser, branch-main

#89 Add openshift-python-wrapper as required
  requirements.txt
  setup.py
Labels: verified, size/XS, Approved-by-rnetser, branch-main

#95 Add openshift-python-wrapper as required
  requirements.txt
  setup.py
Labels: verified, size/XS, branch-v4.12

#98 Remove code-check github action, use tox
  .flake8
  .github/workflows/code-check.yml.old
  .github/workflows/create-auto-pr-for-merge-pr-in-main.yml.xxx
  .github/workflows/upload-to-pypi.yml.xxx
  tox.ini
Labels: verified, size/S, branch-main

#104 Add flake8 to tox.ini
  tox.ini
Labels: verified, size/XS, branch-main

#111 assert_pods_failed_or_pending - add pod namespace
  ocp_utilities/infra.py
Labels: verified, size/XS, Approved-by-myakove, branch-main

#116 run_command - add command timeout
  ocp_utilities/utils.py
Labels: verified, size/XS, Approved-by-myakove, branch-main
