Repository RedHatQE/openshift-python-utilities, pull requests merged in 2023-11, with the labels that each got.

#286 Update pre-commit with ruff
  .flake8
  .isort.cfg
  .pre-commit-config.yaml
  ocp_utilities/debugger.py
  ocp_utilities/infra.py
  ocp_utilities/monitoring.py
  ocp_utilities/operators.py
  ocp_utilities/utils.py
  pyproject.toml
Labels: size/L, verified, branch-main, can-be-merged, approved-rnetser

#288 flake8-plugins pin to version
  .pre-commit-config.yaml
Labels: verified, size/XS, branch-main, can-be-merged, approved-rnetser

#292 Add admin client to resources
  ocp_utilities/infra.py
  ocp_utilities/operators.py
Labels: verified, size/XS, branch-main, can-be-merged, approved-myakove

#290 install operator from source_image
  ocp_utilities/operators.py
Labels: verified, size/M, branch-main, can-be-merged, approved-rnetser, commented-chetna14manku, approved-myakove

#295 Add Prometheus bearer token and fix repo logs formatted strings
  ocp_utilities/infra.py
  ocp_utilities/monitoring.py
  ocp_utilities/operators.py
  ocp_utilities/utils.py
Labels: verified, size/S, branch-main, can-be-merged, approved-rnetser, approved-myakove, commented-omrirh
