Repository RedHatQE/openshift-python-utilities, pull requests merged in 2023-05, with the labels that each got.

#186 run_command: Use subprocess.run
  ocp_utilities/utils.py
Labels: verified, size/S, Approved-by-rnetser, branch-main

#192 adding ICSP config utilities
  ocp_utilities/infra.py
Labels: verified, size/M, Approved-by-myakove, Approved-by-rnetser, branch-main

#197 Add optional parameter tcp_timeout to ssh session
  ocp_utilities/utils.py
Labels: verified, size/XS, Approved-by-myakove, branch-v4.13

#198 install_operator - add operator ns
  ocp_utilities/operators.py
Labels: verified, size/XS, Approved-by-myakove, branch-main

#202 we need to set check=False to triage any must gather failure
  ocp_utilities/must_gather.py
Labels: verified, size/XS, Approved-by-myakove, branch-main, Approved-by-omrirh

#193 Support for creating/updating secrets
  ocp_utilities/infra.py
Labels: verified, size/M, Approved-by-myakove, Approved-by-rnetser, branch-main

#213 metrics query results can be empty
  ocp_utilities/monitoring.py
Labels: verified, size/XS, Approved-by-myakove, Approved-by-rnetser, branch-main

#214 Add operator_namespace to uninstall_operator
  ocp_utilities/operators.py
Labels: verified, size/XS, Approved-by-myakove, branch-main
