Repository RedHatQE/openshift-python-utilities, pull requests merged in 2023-02, with the labels that each got.

#120 Add get_client function
  ocp_utilities/infra.py
Labels: verified, size/S, Approved-by-rnetser, branch-main

#126 auto-cherry-pick: [v4.12] auto-cherry-pick: [v4.13] Add get_client fu…
  ocp_utilities/infra.py
Labels: verified, size/S, branch-v4.11

#128 data_collector - remove openshift-python-wrapper-data-collector
  README.md
  ocp_utilities/data-collector.yaml.example
  ocp_utilities/data_collector.py
  ocp_utilities/infra.py
  setup.py
Labels: verified, size/XL, Approved-by-myakove, branch-main

#132 Remove data_collector
  README.md
  ocp_utilities/data-collector.yaml.example
  ocp_utilities/data_collector.py
  ocp_utilities/infra.py
  setup.py
Labels: verified, size/XL, Approved-by-myakove, branch-v4.12

#135 mget_client - add support for incluster_config
  ocp_utilities/infra.py
Labels: verified, size/S, Approved-by-myakove, branch-main
