Repository RedHatQE/openshift-python-utilities, pull requests merged in 2024-08, with the labels that each got.

#353 prometheus calls should be made with explicitly generated token
  ocp_utilities/monitoring.py
Labels: verified, size/S, branch-main, can-be-merged, approved-myakove

#356 add since and timeout switch to must-gather
  ocp_utilities/must_gather.py
Labels: verified, size/XS, branch-main, can-be-merged, approved-rnetser

#360 [MSINTEROP-1243] Add mirror for registry.stage.redhat.io to ICSP for operator install
  ocp_utilities/operators.py
Labels: verified, size/XS, branch-main, can-be-merged, approved-myakove

#363 Change install_operator to be able to use specific CSV
  ocp_utilities/operators.py
Labels: verified, size/XS, branch-main, can-be-merged, approved-myakove

#361 Update stage ICSP mirror
  ocp_utilities/operators.py
Labels: verified, size/XS, branch-main, can-be-merged, approved-myakove

#364 Add option to uninstall_operator to avoid ns cleanup
  ocp_utilities/operators.py
Labels: verified, size/S, branch-main, can-be-merged, approved-myakove
